name: netflix_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  video_player: ^2.8.3
  cupertino_icons: ^1.0.0
  stroke_text: ^0.0.2
  bordered_text: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  bloc: ^8.1.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  dio: ^5.4.2+1
  get_it: ^7.6.8
  injectable: ^2.4.1
  flutter_native_splash: ^2.4.0  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/